name: .NET Core CI & Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Kéo code về máy ảo Ubuntu của GitHub
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Cài đặt .NET SDK 8 trên máy ảo
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # 3. Tải các gói thư viện NuGet
    - name: Restore dependencies
      run: dotnet restore

    # 4. Biên dịch code C# (kiểm tra lỗi build)
    - name: Build project
      run: dotnet build --no-restore --configuration Release

    # Bước 5: Kiểm tra quá trình đóng gói Docker Image
    - name: Test Docker Image Build
      run: |
        docker build -t devops-api-test:latest ./MyDevOpsApi